/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.swing;

import entities.User;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Area;
import java.awt.geom.Rectangle2D;
import java.awt.geom.RoundRectangle2D;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import repository.HibernateUtils;
import repository.UserRepository;
import view.Home;

/**
 *
 * @author alber
 */
public class LoginForm extends javax.swing.JPanel {

  
        private int round = 50;
        User user = new User();
        UserRepository userRepository = new UserRepository();

        /**
         * Creates new form LoginForm
         */
        public LoginForm() {
                initComponents();
                createAdmin(user);
                setOpaque(false);
                setBackground(new Color(255, 255, 255));
                setForeground(new Color(255, 255, 255));
        }
        
        //Método para validar usuario
        public boolean validateUser() {
                String username = tf_username.getText();
                String password = pf_password.getText();

                try {
                        if (username.equals("")) {
                                JOptionPane.showMessageDialog(this, "Enter an username");
                        } else if (password.equals("")) {
                                JOptionPane.showMessageDialog(this, "Enter a password");
                        }
                } catch (HibernateException e) {
                        System.err.println("Error al iniciar sesión");
                        System.err.println(e.getMessage());
                }

                return true;
        }

        //Método para encontrar usuario en la BD
        protected Boolean findUser(String username, String password) {
                boolean found = false;
                Session session = HibernateUtils.openConnection();
                try {
                       session.beginTransaction();
                        String query = "FROM User WHERE username = '" + username + "'";
                        List<User> users = session.createQuery(query).list();
                        for (User tempUser : users) {
                                if (tempUser.getPassword().equals(password)) {
                                        found = true;
                                        break;
                                }
                        }
                        session.getTransaction().commit();

                } catch (HibernateException e) {
                        session.getTransaction().rollback();
                        System.err.println("Unregistered user");
                        System.err.println(e.getMessage());
                }
                return found;
        }
        
        public void createAdmin(User user){
                 Session session = HibernateUtils.openConnection();
                if (findUser(tf_username.getText(), pf_password.getText()) == false) {
                        try {
                                user.setName("Admin");
                                user.setSurnames("admin admin");
                                user.setUsername("admin");
                                user.setPassword("1234");
                                user.setEmail("admin@gmail.com");
                                user.setPhone("666778899");
                                userRepository.create(user);
                } catch (Exception e) {
                        System.err.println(e.getMessage());
                        session.getTransaction().rollback();
                        System.out.println("Error creating user");
                }
                } else{
                        System.out.println("User already exists");
                }
        }
        
        

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        
        public void initSystemBtnLabel(JFrame frame, LoginForm loginForm){
                systemBtnLabel.initEvent(frame, loginForm);
        }
        
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                systemBtnLabel = new view.swing.SystemBtnLabel();
                btn_login = new view.swing.MyButton();
                pf_password = new view.swing.PasswordField();
                tf_username = new view.swing.TextField();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();

                setBackground(new java.awt.Color(255, 255, 255));
                setPreferredSize(new java.awt.Dimension(525, 750));

                btn_login.setBackground(new java.awt.Color(69, 39, 160));
                btn_login.setBorder(null);
                btn_login.setForeground(new java.awt.Color(255, 255, 255));
                btn_login.setBorderColor(new java.awt.Color(69, 39, 160));
                btn_login.setColor(new java.awt.Color(69, 39, 160));
                btn_login.setColorClick(new java.awt.Color(0, 0, 112));
                btn_login.setColorOver(new java.awt.Color(0, 0, 112));
                btn_login.setFont(new java.awt.Font("Rubik SemiBold", 1, 16)); // NOI18N
                btn_login.setLabel("Login");
                btn_login.setRadius(25);
                btn_login.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_loginActionPerformed(evt);
                        }
                });

                pf_password.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
                pf_password.setLabelText("Password");
                pf_password.setLineColor(new java.awt.Color(109, 109, 109));

                tf_username.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
                tf_username.setLabelText("Username");
                tf_username.setLineColor(new java.awt.Color(109, 109, 109));

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/farmer.jpg"))); // NOI18N

                jLabel2.setFont(new java.awt.Font("Rubik Light", 1, 24)); // NOI18N
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setText("The home of healthy lifestyle");
                jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

                jLabel3.setFont(new java.awt.Font("Rubik SemiBold", 1, 32)); // NOI18N
                jLabel3.setText("Welcome to NaturPoint");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(464, Short.MAX_VALUE)
                                .addComponent(systemBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(208, 208, 208)
                                                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(73, 73, 73)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(98, 98, 98)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(systemBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
                validateUser();
                 if (findUser(tf_username.getText(), pf_password.getText())) {
                        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                        frame.dispose();
                        Home home = new Home();
                        home.setVisible(true);
                } else {
                         JOptionPane.showMessageDialog(null, "Login details incorrect");
                        pf_password.setText("");
                }
        }//GEN-LAST:event_btn_loginActionPerformed


        @Override
        public void paint(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                int width = getWidth();
                int height = getHeight();

                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, width, height, round, round);
                Area area = new Area(new RoundRectangle2D.Double(0, 0, width, height, round, round));
                area.add(new Area(new Rectangle2D.Double(0, height, width, 10)));
                g2.setColor(getForeground());
                g2.fill(area);
                g2.dispose();
                super.paint(g);
        }
        
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private view.swing.MyButton btn_login;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private view.swing.PasswordField pf_password;
        private view.swing.SystemBtnLabel systemBtnLabel;
        private view.swing.TextField tf_username;
        // End of variables declaration//GEN-END:variables
}
