/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.swing;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;

/**
 *
 * @author alber
 */
public class SystemBtnLabel extends javax.swing.JPanel {

    /**
     * Creates new form SystemBtnLabel
     */
    public SystemBtnLabel() {
        initComponents();
        setBackground(new Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void initEvent(JFrame frame, LoginForm loginForm){
        close_label.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent me){
                setForeground(new Color(24, 24, 240));
                System.exit(0);
            }
            @Override
            public void mousePressed(MouseEvent me){
                setForeground(new Color(24, 24, 240));
            }
        });
        
    }
    
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                close_label = new javax.swing.JLabel();

                close_label.setBackground(new java.awt.Color(255, 255, 255));
                close_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                close_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(close_label, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(close_label, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel close_label;
        // End of variables declaration//GEN-END:variables
}
